### ISSUE TITLE
 { AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded.

### ISSUE THREAD

**Issue by Cody1988** [weexteam/weex-debugger#1]
when I run the weex project width command

```bash
weex debugx src/index.vue
```

there is an error

``` exception
Launching Dev Tools...
Starting inspector on port 9999
Unhandled Rejection at: Promise {
  <rejected> { AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
    at Console.assert (console.js:191:23)
    at Function.launch (/Users/cody/.xtoolkit/node_modules/puppeteer/lib/Launcher.js:92:15)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' } } reason: { AssertionError [ERR_ASSERTION]: Chromium revision is not downloaded. Run "npm install"
    at Console.assert (console.js:191:23)
    at Function.launch (/Users/cody/.xtoolkit/node_modules/puppeteer/lib/Launcher.js:92:15)
    at <anonymous>
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }


```

**Comment by erha19** [comment]
@Cody1988 you have no install right dependence. try:
choose correct `npm` origin,`https://registry.npmjs.org/` or `https://registry.npm.taobao.org/`
```
rm -rf ~/.xtoolkit/node_modules/weex-debugger
weex config registry https://registry.npmjs.org/
weex debugx
```

**Comment by ggchxx** [comment]
run 
weex config registry https://registry.npm.taobao.org/
weex debug
the log tips：
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz

**Comment by erha19** [comment]
@ggchxx @Cody1988 [Chinese Document](https://github.com/weexteam/weex-toolkit/blob/master/README-zh.md#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) this document should help for you.
