### ISSUE TITLE
debugger报错

### ISSUE THREAD

**Issue by fanlvwen** [weexteam/weex-debugger#11]
现在已经可以连上debugger服务，但是客户端原生代码报错
[WXBridgeManager] invokeInitFramework java.lang.AbstractMethodError: abstract method "int com.taobao.weex.common.IWXBridge.initFrameworkEnv(java.lang.String, com.taobao.weex.bridge.WXParams, java.lang.String, boolean)"
                                                        at com.taobao.weex.bridge.WXBridgeManager.initFramework(WXBridgeManager.java:1795)
                                                        at com.taobao.weex.bridge.WXBridgeManager.invokeCreateInstance(WXBridgeManager.java:1574)
                                                        at com.taobao.weex.bridge.WXBridgeManager.access$400(WXBridgeManager.java:110)
                                                        at com.taobao.weex.bridge.WXBridgeManager$9.run(WXBridgeManager.java:1558)
                                                        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
                                                        at android.os.Handler.handleCallback(Handler.java:743)
                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                        at android.os.Looper.loop(Looper.java:150)
                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

关闭debug模式，加载apk中的js没问题，请看一下。我是直接 WXEnvironment.sDebugServerConnectable = true;
        WXEnvironment.sRemoteDebugMode = true;
开启的debug

**Comment by erha19** [comment]
see https://github.com/weexteam/weex-toolkit/issues/517
